image: docker:latest

stages:
  - build
  - push

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY_IMAGE: registry.gitlab.com/khodemun/ui-infra

before_script:
  - apk add --no-cache docker-cli # Ensure docker command is installed
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

build_frontend:
  stage: build
  script:
    - docker build -t $REGISTRY_IMAGE:latest .
    - docker push $REGISTRY_IMAGE:latest
  only:
    - main
