module.exports = {
  content: [
    "./src/**/*.{html,ts}",
    "./projects/**/*.{html,ts}",
    "./node_modules/flowbite/**/*.js",
  ],
  theme: {
    extend: {
      colors: ({ theme }) => ({
        info: "#539bff",
        success: "#13deb9",
        warning: "#ffae1f",
        error: "#fa896b",
        lightsuccess: "#13deb920",
        lighterror: "#fa896b20",
        lightinfo: "#ebf3fe",
        darkinfo: "#223662",
        lightwarning: "#ffae1f20",
        white: "#fff",
        dark: "#202936",
        border: "#dfe5ef",
        darkborder: "#333f55",
        link: "#2a3547",
        muted: "#5a6a85",
        darklink: "#7c8fac",
        lightgray: "#f6f9fc",
        bgmuted: "#eff4fa",
        darkgray: "#465670",
        bodytext: "#5a6a85",
        erroremphasis: "#d5745b",
        darkmuted: "#2a3851",
        lightmuted: "#5d7287",
        warningemphasis: "#d9941a",
        successemphasis: "#10bd9d",
        infoemphasis: "#3184f7",
        grayemphasis: "#99aaba",
        lightemphasis: "#dfe5ef",
        primary: "#5d87ff",
        primaryemphasis: "#4f73d9",
        secondary: "#49beff",
        secondaryemphasis: "#3ea2d9",
        border: "#dfe5ef",
        lightprimary: "#5d87ff20",
        lightsecondary: "#49beff20",
      }),
    },
  },
  plugins: [require("flowbite/plugin")],
};
